version: '3.9'

services:

  s-order:
    build: ./s-order
    ports:
      - "8080:8081"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_ORDER}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - app-network

  s-product:
    build: ./s-product
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_PRODUCT}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - app-network

  s-payment:
    build: ./s-payment
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL_PAYMENT}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:17
    restart: always
    ports:
      - "5469:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infras/sql/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - app-network

networks:
  app-network:

volumes:
  postgres-data: {}
