spring:
  application:
    name: s-order

  datasource:
    url: jdbc:postgresql://db:5469/db_order
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer