spring:
  application:
    name: s-product

#  datasource:
#    url: ${SPRING_DATASOURCE_URL}
#    username: ${SPRING_DATASOURCE_USERNAME}
#    password: ${SPRING_DATASOURCE_PASSWORD}
#    driver-class-name: org.postgresql.Driver

  datasource:
    url: jdbc:postgresql://localhost:5469/postgres
    username: postgres
    password: 1
    driver-class-name: org.postgresql.Driver

server:
  port: 8082
